# Generated by Django 5.1.2 on 2024-10-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('user_image_id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('description_encoded_64', models.CharField(default='', max_length=100000)),
                ('birth_date', models.DateField(default='1970-01-01')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rizzder_app.userimage')),
            ],
        ),
    ]
