# Generated by Django 5.1.2 on 2024-10-28 18:31

import django.db.models.deletion
import rizzder_app.entity.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('user_image_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.CharField(default='', max_length=1000)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=1000)),
                ('description_encoded_64', models.CharField(default='', max_length=100000)),
                ('birth_date', models.DateField(default='1970-01-01')),
                ('gender', models.IntegerField(default=rizzder_app.entity.user.Gender['MAN'], verbose_name=rizzder_app.entity.user.Gender)),
                ('gender_preference', models.IntegerField(default=rizzder_app.entity.user.Gender['MAN'], verbose_name=rizzder_app.entity.user.Gender)),
                ('credential', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(to='rizzder_app.userimage')),
            ],
        ),
    ]
