# Generated by Django 5.1.2 on 2024-10-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzder_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
