# Generated by Django 5.1.2 on 2024-10-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rizzder_app', '0003_user_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='images',
        ),
    ]
